name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build ./SampleSolution/sample/sample.csproj
    - name: Test
      run: dotnet test --verbosity normal ./SampleSolution/sample.unittests/sampleunittests.csproj
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Archive
        path: |
          ./SampleSolution/bin
